export {default as VideoPlayer} from "./VideoPlayer/VideoPlayer"
export {default as Navbar} from "./navbar/navbar"
export {default as ModalLogin} from "./modal/ModalLogin"
export {default as ModalSignin} from "./modal/ModalSignin"
export {default as ModalSignup} from "./modal/ModalSignup"
export {default as Carousel} from "./carousel/Carousel"
export {default as VideoUpload} from "./videoUpload/VideoUpload"
export {default as Footer} from "./footer/footer"
export {default as Profile} from "./profile/ProfileComponent"
export {default as Headline} from "./headline/Headline"
export {default as Box} from "./box/box"
export {default as Testimoni} from "./testimoni/testimoni"
export {default as ModalFailed} from "./modal/ModalFailed"
export {default as Leaderboard} from "./leaderboard/Leaderboard"
export {default as GameRPS} from "./games/Games"
export {default as GamesDetails} from "./landingGame/LandingGames"
export {default as Histori} from "./history/History"
// export {default as ProfileVideo} from "./videoUpload/ProfileVideo"